### ISSUE TITLE
Infinite scroll example should not rely on a polyfill

### ISSUE THREAD

**Issue by vvo** [algolia/vue-instantsearch#149]
It's sad but the Intersection Observer API is not fully supported by browsers (namely, all Safari versions).

Let's use something that does not requires the user to provide a polyfill (or at least includes the polyfill in a way in the example) since detecting for scroll position has been around for years (even without the new browser API).

Example: https://github.com/vvo/in-viewport (old, might find better alternatives now)

**Comment by rayrutjes** [comment]
Wasn't aware of your package, impressive ;)

I actually chose to go down to polyfill path because I thought it was the best future proof way to tackle the use case.

Not using a polyfill approach would mean having less good perfs than the native Observer API I guess. 

As for now, this is not part of the library anyway, it is just 1 example of how to achieve the detection.

I do not feel comfortable shipping any kind of visibility detection library as part of Vue InstantSearch given it just aims to solve a very small feature of a single component.

I'd gladly leave this up to the user anyway.

I'd love to hear more about the pros of going with a dedicated library.

**Comment by vvo** [comment]
Sorry I was not clear enough. What I missed from the example is that it says "You should include a polyfill, see this repo".

Then you end up on a repo that says "you should include a polyfill" without a good explanation on how to actually do this.

As for our own examples, they need to work in all major browsers (which is not the case here, safari fails).

So this example should have its own code including the actual needed polyfill for it to be complete.

So you can remove the links to that GitHub repo and just add a comment in the code saying "This is to support observer API in safari, ..".

Example: https://cdn.polyfill.io/v2/polyfill.js?features=IntersectionObserver (in chrome this leads to an empty file, in safari this leads to the polyfill).

Or with npm: https://yarnpkg.com/en/package/intersection-observer

**Comment by rayrutjes** [comment]
Opened this on the relevant repository ;)
