### ISSUE TITLE
Migrate to new Helper and JS Client

### ISSUE THREAD

**Issue by bobylito** [algolia/vue-instantsearch#197]
In the coming months, we'll have new versions of the client and the helper. Let's get ready :)
https://github.com/algolia/algoliasearch-helper-js/issues/521

**Comment by rayrutjes** [comment]
So according to @Haroenv comment, for now:
- we don't use methods that return promises
- we don't use deprecated methods
- we don't use initIndex

We will need to review the import strategy when the 2 libs get release though. Nothing actionable as of now if I'm not mistaken.

Let me know if there is something we could already do. Otherwise I'll close this until we have the 2 new versions.

**Comment by Haroenv** [comment]
It's early to already think about the migration, the complicated part here should normally be handled by the helper, since it's a dependency

**Comment by rayrutjes** [comment]
Can't wait to make the lib compatible with the new versions here to leverage tree shaking 🎉 
Closing this for now until we can move forward.

**Comment by bobylito** [comment]
> Nothing actionable as of now if I'm not mistaken.

Indeed, just wanted to bring awareness. :)
