### ISSUE TITLE
Add infinite pagination capability

### ISSUE THREAD

**Issue by konstantinrachev** [algolia/vue-instantsearch#304]
**Do you want to request a *feature* or report a *bug*?**
I would like to propose a new feature. Adding a lazy load module would be a great add-on.

**Feature: What is your use case for such a feature?**
As pagination is getting a little bit out-of-date, I would propose to add a implementation of an lazy load mechanism. My vision is to get the results like from the pagination one, but when I scroll and get to the end, the Algolia instance would send a request and load the next portion of my results.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
The proposed entry would be addition to the ```ais-index``` or component like the pagination one, which will accept mainly 2 params: ```number of results```(to lazy load) and ```preloader```.

The option would give us the opportunity to use either the pagination component, or the lazy-load one, but not both.

**Comment by rayrutjes** [comment]
Hey @konstantinrachev ,

Did you maybe checkout https://community.algolia.com/vue-instantsearch/examples/infinite-scroll.html ?

Currently we accept a property called `stack` on the `ais-results`.
When set to `true`, it will stack the results instead of removing results from previous page.

All you have to do is determine when and how you want to trigger the next page load.

**Comment by rayrutjes** [comment]
Hey @konstantinrachev ,

Have you been able to implement this?
For now, we are not planning on implementing a specific component here given the scope really depends on the user experience you want to build.

Please share your implementation or discuss the feature on our forum: https://discourse.algolia.com/
