### ISSUE TITLE
Make sure ais-stats doesn't disappear

### ISSUE THREAD

**Issue by michtio** [algolia/vue-instantsearch#417]
currently the stats part is removing the html and the block when the result returns zero, for UX it would be better if you have a search and the search doesn't return any results, the `ais-stats` returns "0 results found" instead of just removing everything.

```
 <div :class="bem()" v-if="totalResults > 0">
    <slot :totalResults="totalResults" :processingTime="processingTime" :query="query">
      {{ totalResults.toLocaleString() }} results found in {{ processingTime.toLocaleString() }}ms
    </slot>
  </div>
```

can easily be adjusted with the removal of  `v-if="totalResults > 0"` for a end-user it is always strange to see information and all of the sudden it disappears, currently you can solve it by 

```
<ais-stats></ais-stats>
<ais-no-results></ais-no-results>
```

but from the vision of an optimiser this just adds code where actually there shouldn't be any code ...

**Comment by Haroenv** [comment]
Good point, let's put this behaviour behind an option, because the default behaviour is hiding in other versions of InstantSearch too, in favour of replacing the hits with some display for "no hits found" rather than reusing the stats. 


`v-if="autoHide && totalResults > 0"`

with `autoHide` being a prop that defaults to true. Do you want to make a PR for this?

**Comment by Haroenv** [comment]
In v2 this conditional is not in place anymore.
