### ISSUE TITLE
Invoke function on keyup event

### ISSUE THREAD

**Issue by jack-pallot** [algolia/vue-instantsearch#514]
I need to re-render a part of UI on the page whenever the search query changes. Initially, I've tried to setup a watcher on the input query, but I can't seem to access the value. Here's what I'm trying to do in Vanilla JS, I just need a way of converting this to use within Vue.

```
const el = document.querySelector('.ais-input')

el.addEventListener('keyup', function() {
  setTimeout(function() {
    console.log('changed')
  }, 1000)
})

```
 Is there an emitted event, or a way of accessing this data? Any help would be appreciated.

**Comment by Haroenv** [comment]
It would indeed be more vue-like to do something based on the query, rather than the keyup there. 

The way you would do that is the following: 

1. make a custom component
2. use the Algolia component mixin
3. use the query wherever on `this.searchStore`

The code of that component would look like this: 

```vue
<template>
  <div>
    Hi there! Query is <strong>"{{searchStore.query}}"</strong>
  </div>
</template>

<script>
import {Component} from 'vue-instantsearch'
export default {
  mixins: [Component],
  watch: {
    'searchStore.query'(newQuery, oldQuery) {
      console.log(
        'use this for side effects',
        newQuery,
        oldQuery
      );
    }
  }
}
</script>
```

I made an example here: https://codesandbox.io/s/z5718oqm3

I hope that helps, but please reopen if you have any more questions!
