### ISSUE TITLE
Can't figure out how to do routing(not vue-router) in v2

### ISSUE THREAD

**Issue by jondcampbell** [algolia/vue-instantsearch#543]
**Feedback on the v2 alpha version 🆕**

### Describe the bug / features

We are basically trying to do up some custom routing using built-in routing functionality but can't seem to get it working on v2.

The documentation we have to work with is this non-vue code: https://community.algolia.com/instantsearch.js/v2/guides/routing.html#seo-friendly-urls

We know routing can be turned on based on this example:
https://codesandbox.io/s/qlzpx9vkwq?module=%2Fsrc%2FApp.vue

But we can't the custom routing working. We aren't sure how to reference the instantsearch.routes.history() within our router object. (See line 133 of our reproduction [codebox](https://codesandbox.io/s/1v32772954?module=%2Fsrc%2FApp.vue))

### Reproduction

We took a basic v2 routing example and mixed in the custom routing settings to try and get it working:
https://codesandbox.io/s/1v32772954?module=%2Fsrc%2FApp.vue

### How to resolve or implement the fix?

Explain how this can be done on v2? 

### What is the version you are using?

v2.0.0-alpha.3

**Comment by Haroenv** [comment]
This is how you import the history router from InstantSearch.js and customise it as in the example:

https://codesandbox.io/s/q8pmz6n7lj

**Comment by Haroenv** [comment]
I will close this now, since the immediate problem is solved (importing the history router), but I will open a new issue more general purpose for strategies how to deal with routing. For now the advice is to use the instantsearch router and modify it like that. To combine with vue router is also possible, but the default strategies don't "talk" to vue router, which means that more advanced usage where you want to read the query string to do things with it, need to happen within the instantsearch router, not within the vue router
