### ISSUE TITLE
v2:  "Error: routing configuration can not be changed dynamically at this point."

### ISSUE THREAD

**Issue by ul8** [algolia/vue-instantsearch#583]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

I'm getting these error messages:

`[Vue warn]: Error in callback for watcher "routing": "Error: routing configuration can not be changed dynamically at this point.`

as well as

`Error: routing configuration can not be changed dynamically at this point.`

I am not consciously changing the router configuration anywhere, not changing indexes either.

Under what circumstances are these messages triggered?

### Reproduction

The errorrs show up here:
https://codesandbox.io/s/3xm9y06y25

using v2.0.0-beta.1

**Comment by Haroenv** [comment]
This is because you wrote it as an inline object. Vue will not diff the object (since the keys are functions). This means that the whole routing object should be “static”, I.e. created in your data and passed as a single variable. This is normal in Vue if you make objects or arrays in render that they get renewed every rendering

**Comment by ul8** [comment]
Thanks, that worked. Note I copied the code from the first example on this page, you might want to change the code there too.

https://v2--vue-instantsearch.netlify.com/advanced/vue-router-url-sync.html

**Comment by Haroenv** [comment]
This has been updated since in the v2 docs, but also in the new documentation; see https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/
