### ISSUE TITLE
v2 Use ais-numeric-menu with ais-configure

### ISSUE THREAD

**Issue by leonardovilarinho** [algolia/vue-instantsearch#599]
**Bug 🐞**

### What is the current behavior?

I am trying to use the numeric menu, but as I have the configuration of numericFilters it ends up giving an error filtering the value through the menu.

### Make a sandbox with the current behavior

```
<ais-instant-search :search-client="searchClient" :index-name="getProductIndex">
  <ais-configure :numericFilters="['in_stock=1', 'visibility_catalog=1']"/>
  <div class="category--filters_price">
    <h3>Prices</h3>
    <ais-numeric-menu
      attribute="price.BRL.default"
      :items="[
        { label: 'All' },
        { label: 'At U$ 25', end: 25 },
        { label: 'U$ 25 at U$ 75', start: 25, end: 75 },
        { label: 'U$ 75 at U$ 150', start: 75, end: 150 },
        { label: 'More U$ 150', start: 150 },
      ]"
    />
  </div>

  <ais-infinite-hits>
    <template slot="default" slot-scope="{ items, refine, isLastPage }">
      <div class="category--products row">
        <div class="row">
          <div v-for="(item, itemIndex) in items" :key="itemIndex">
            <product-card :product="item" :lazy="false"/>
          </div>
        </div>

        <div class="infinite" style="width: 100%">
          <button v-if="!isLastPage" @click="refine" class="button loadmorebutton">Carregar mais</button>
        </div>
      </div>
    </template>
  </ais-infinite-hits>
</ais-instant-search>
```

### What is the expected behavior?
The numerical menu concatenates the filter with the already defined in ais-configure, so we may not have the error.

### Does this happen only in specific situations?
Only when you have two numeric filters, in the case in the menu and in ais-configure.

### What is the proposed solution?
When changing the value of the numerical menu, check if there is a numerical filter in ais-configure and then concatenate the value of both.

### What is the version you are using?
2.0.0-beta.1

**Comment by samouss** [comment]
Indeed but this is an expected behaviour at the moment. We have a similar issue with [React InstantSearch](https://github.com/algolia/react-instantsearch/issues/1490). Right now the workaround is to use [`filters`](https://www.algolia.com/doc/api-reference/api-parameters/filters/) rather than [`numericFilters`](https://www.algolia.com/doc/api-reference/api-parameters/numericFilters/) inside `ais-configure`.

I transfer the issue because Vue InstantSearch is not responsible of this issue. The logic that manages the search is inside [InstantSearch.js](https://github.com/algolia/instantsearch.js). I've opened [an issue](https://github.com/algolia/instantsearch.js/issues/3384) about that.
