### ISSUE TITLE
Numeric Filter: AND / OR

### ISSUE THREAD

**Issue by MrRossBennett** [algolia/vue-instantsearch#638]
Hello Algolia

We'd like to be able to construct an AND and an OR query that powers a numeric filter.

For example, when using the `ais-range-input` we'd like to return all items that have a value between our min and max values (i.e the default behaviour) AND all items that have a value of 0. 

So the query would be `(value >= $minValue AND value <= $maxValue) OR value = 0`

We've tried to do this via the filters prop on the `ais-configure` component but it seems to stop the range input from functioning. 

How would we go about creating a query like this using the vue-instantsearch components?

Thanks very much

**Comment by Haroenv** [comment]
Hi @MrRossBennett,

Do I understand it correctly that the value of the minValue & maxValue should be dictated by the input, but always the option of 0 should also be shown? This is not a use case our widgets are designed for, since they all assume a refinement is "conjunctive" (and) , and thus if you want to add a widget + the extra condition with configure, it's considered as a conjunction.

A possible solution I see is crafting the `filters` property yourself based on both inputs (and setting with a configure e.g.), and not using our widget, but before explaining how that I'd like to be sure I correctly understand your use case

Could you show which use case you have with this template? https://codesandbox.io/s/wn155885j7

**Comment by MrRossBennett** [comment]
Hello @Haroenv 

Yes, that's exactly right - the value of the minValue & maxValue should be dictated by the input, but always the option of 0 should also be shown.

Your suggestion of crafting the filters property ourselves via `ais-configure` sounds interesting. Be great to know the best way to do that. (Ah, in order to show the issue via the template you provided, we'd need some items that have a price of 0, but you've understood the question correctly anyway). 

Thanks again

**Comment by Haroenv** [comment]
This is how you would do that: https://codesandbox.io/s/wn155885j7 (approximately, I didn't read from the possible values since that's quite a bit harder. 

Note I had to change your filter because Algolia doesn't allow `(X AND Y) OR Z`, but it does allow `(X OR Z) AND (Y OR Z)`

**Comment by MrRossBennett** [comment]
Brilliant :+1:. Thanks @Haroenv.
