### ISSUE TITLE
Disable-only option for refinement-list

### ISSUE THREAD

**Issue by Finnepinnen** [algolia/vue-instantsearch#660]
**Feature ⚡️**

### What is your use case for such a feature?
To make the interface mor consistent and to reduce jumps as the faceting options are reduced.

### What is your proposal
Instead of reducing the number of items just disable them.

### What is the version you are using?
V2.0

**Comment by Haroenv** [comment]
This is an existing limitation, so the suggested solution is fairly lacking, but if you have a static list of items; you can solve it like this: https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/vue/#add-manual-values

```vue
<template>
<ais-refinement-list
  attribute="categories"
  :transformItems="getStaticValues"
/>

</template>

<script>
// There is a limitation here with our helper/is.js based libraries
// we do not provide values that were refined and that have 0 count
// In this case, this is problematic because a correct implementation should
// keep track of the selected values and implementing in this situation would
// be a lot of code.
export default {
  methods: {
    getStaticValues: (items) => {
      const staticValues = ['Cell Phones', 'Unlocked Cell Phones'];
      return staticValues.map(value => {
        const item = items.find(item => item.label === value);
        return item || {
          label: value,
          value,
          count: 0,
          isRefined: false,
          highlighted: value,
        };
      });
    }
  }
};
</script>
```

This is a limited version, because it will always keep the ordering of your static list, unless you sort it yourself after, but it will show the static list of items you want, with a correct count.

**Comment by deanL-zuiderlicht** [comment]
And what if the list is not static?
