### ISSUE TITLE
GeoSearch - this.$refs not available in `mounted()` function

### ISSUE THREAD

**Issue by regenrek** [algolia/vue-instantsearch#681]
**Bug 🐞**

### What is the current behavior?

I reproduced the GeoSearch [example](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/geo-search/vue/) from the official algolia docs. 

* In the example the map is wrapped with `v-if="this.state"` so you don't run in errors as long as the state isn't available yet.
* This solutions works but prevents that `this.$refs` is available in `mounted()` hook i guess. Also `this.state` isn't available in `mounted()`.

_Additional Info:_ chrome dev tools output this info too if you use the geosearch connector.

![](https://i.imgur.com/eZ8dJmT.png)

### Demo Sandbox

https://codesandbox.io/embed/algolia-vueinstantsearch-v3-geosearch-c08m6

### What is the expected behavior?

- You should have access to `this.$refs` property in mounted() hook.
- Or maybe you get an `promise` or some `event` where you can hook in when the  `state` from the `geosearch connector` is available

```js

  mounted() {
    // Accessing leaflet API methods according to
    // @link https://korigan.github.io/Vue2Leaflet/#/quickstart?id=accessing-leaflet-api

    // mapObject is undefined !!!!!
    this.$nextTick(() => {
      this.map = this.$refs.mapRef.mapObject;
      this.map.zoomControl.remove();
      console.debug(this.$refs.mapRef.mapObject);
    });

    // state is null
     for (let item of this.state.items) {
      item.icon = this.defaultIcon;
    }
  },

```

### What is the proposed solution?

`this.state` and `this.$refs` should be available in `mounted()`. 

**EDIT: 06/04**

Ok I can propose a simple solution here:

#### Move `v-if="state"` inside `<googlemaps-map>`

```diff
<template>
-  <div v-if="state" class="ais-GeoSearch">
+ <div class="ais-GeoSearch">
    <googlemaps-map
      :center="center"
      :zoom.sync="zoom"
      class="ais-GeoSearch-map"
      ref="mymap"
    >
+ <div v-if="state">
<googlemaps-marker
        v-for="item of state.items"
        :key="item.objectID"
        :title="item.name"
        :position="item._geoloc"
      />
+ </div>
    </googlemaps-map>
  </div>
</template>

<script>
export default {
  data() {
    return {
      center: {lat: 0, lng: 0},
      zoom: 12,
    };
  },
  mounted() {
    // 
    console.debug(this.$refs.mymap)
  }
};
</script>
```

### What is the version you are using?

vue-instantsearch 2.2.1

I will this here if someone run in to the same isue

**Comment by samouss** [comment]
> Move `v-if="state"` inside `<googlemaps-map>`

The proposed solution is definitely the way to go for this use case. We might revisit the needs of the `v-if` in a future release because it should not be a concern for end-users. It's an implementation detail that should not be present at this level.

> _Additional Info:_ chrome dev tools output this info too if you use the geosearch connector.
> 
> ![](https://i.imgur.com/eZ8dJmT.png)
>

Yes, this warning is expected. The option `enableGeolocationWithIP` was available and enabled by default inside the previous version of InstantSearch.js (which Vue InstantSearch uses internally). We dropped this option inside the latest major version. To ease the transition for the users we added a warning with the proposed alternative. The drawback is that the warning is always displayed since the value was enabled by default.

-----

I'll close the issue since you provided a solution to the problem. Thanks again!
