### ISSUE TITLE
ClearRefinements component cannot override default slot

### ISSUE THREAD

**Issue by kevintruby** [algolia/vue-instantsearch#712]
**Bug 🐞**

### What is the current behavior?
`<ais-clear-refinements>` component does not override the template via default slot, as per [the documentation](https://www.algolia.com/doc/api-reference/widgets/clear-refinements/vue/#customize-the-ui). The default template continues to be rendered, regardless of what is passed into the default slot.

### Make a sandbox with the current behavior

https://codesandbox.io/s/vue-instantsearch-app-fkwdm -- _see line 25 of `App.vue`, where the override takes place._

### What is the expected behavior?
Default slot should be overridden. In the case of the documentation, and the codesandbox link above using the example from documentation, an `<a>` element should be rendered in place of a `<button>` element, _and this should only occur if there is a state to refine_, as opposed to always rendering and providing a `:disabled` attribute.

### Does this happen only in specific situations?
No, seems to happen generally.

### What is the proposed solution?
The default slot does not appear to make use of the `v-bind` directive, so perhaps it is a simple fix? I'm comparing to the `AisStats` [component source code](https://github.com/algolia/vue-instantsearch/blob/master/src/components/Stats.vue) for reference.

### What is the version you are using?
Latest version: `2.3.0`.
> Always try the latest one before opening an issue.

**Comment by samouss** [comment]
The behavior observed is the one expected. It's not related to Vue InstantSearch but more Vue in general. The link inside the slot is rendered only when `canRefine` is `true`. By default, its value is `false` because we don't have any refinements, which means that nothing is rendered. Nothing is rendered so Vue picks the default slot, that explains why the override seems to be ignored. You can refine an element inside the `refinementList` and override will be taken into account.

You can fix this an empty element rather than don't render anything. I've updated [the example](https://codesandbox.io/s/vue-instantsearch-hidden-clearrefinements-kk57x), it should now work as expected. I'll create a PR on the documentation to fix the snippet, to avoid this issue.

**Comment by kevintruby** [comment]
@samouss I feel like a dummy now, this makes complete sense and I didn't pause to think about how a component would react if the _attempted_ slot override didn't render due to a `v-if` directive; that it would fall back to the _actual_ default slot.

Thank you for pointing this out, and updating the example link, I greatly appreciate it 😄
