### ISSUE TITLE
Accessing the result hits directly

### ISSUE THREAD

**Issue by stephan-v** [algolia/vue-instantsearch#716]
The `<ais-state-results>` component allows you to access the `hits` in a `slot-scope` but is there also a way I can just access the results from Algolia in a more `programmatic` way(for the lack of a better word)?

I need to fetch my data and send some of it over to a Google Maps implementation so I need to input the results from Algolia into a Vuex store.

Cheers.

**Comment by Haroenv** [comment]
You can have access to components' data in life cycles if you use the "custom" widget: https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/vue/

Your custom data could be implemented like this:

```js
// HitsInjector.js

import { connectHits } from 'instantsearch.js/es/connectors';
import { createWidgetMixin } from 'vue-instantsearch';

export default {
  mixins: [createWidgetMixin({ connector: connectHits })],
  watch: {
    'state.hits'(prev, next) {
      // do whatever you want here, e.g. add in store
      console.log(prev, next);
    },
  },
  render() {
    return null;
  },
};
```

Then you add that within your InstantSearch component. 

However, I'd advice you not to sync hits in a store, since it'll be easy to make mistakes which cause unexpected rerenders or data desync. 

example: https://codesandbox.io/s/vue-instantsearch-app-hsqkb

You can instead also implement your google maps widget in the way i explained here. there's a guide for maps here: https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/geo-search/vue/
