### ISSUE TITLE
Multiple calls to the api when adding :sort-by attribute on ais-refinement-list component

### ISSUE THREAD

**Issue by marekalgoud** [algolia/vue-instantsearch#718]
**Bug 🐞**

### What is the current behavior?

When I add the :sort-by attribute on an ais-refinement-list component, the script make many request to the server instead of one. 
When I remove it, the app works fine

### Make a sandbox with the current behavior

Impossible to reproduce on sandbox...

### What is the expected behavior?

Just one request even with :sort-by attribute

### Does this happen only in specific situations ?

I've tried with or without a ais-configure component (as describe here https://discourse.algolia.com/t/ais-configure-cause-multiple-hit-to-algolia-api-doubling-the-facet-filter/7565), but I've always the same behaivor

### What is the version you are using?

"vue": "^2.6.10",
"algoliasearch": "^3.34.0",
"vue-instantsearch": "^2.4.0",

> Always try the latest one before opening an issue.

**Comment by tkrugg** [comment]
Hi @marekalgoud, it might be that you are passing a new reference everytime, which triggers a rerender and therefore a new request. Can you briefly show us how your declared your component and the value you're passing in the sort-by prop?

**Comment by tkrugg** [comment]
@marekalgoud try putting the sort-by attribute in data, and let me know how it goes.
```js
<ais-refinement-list ...  :sort-by="sortBy" />


export default {
  data() {
    return {
      sortBy: ['name:asc'],
    };
  },
};
```

**Comment by marekalgoud** [comment]
Hello @tkrugg ,

I've tried it and it works ! Thanks for your help. Could you just explain me why this behaves like this ? 

Thanks again !

**Comment by Haroenv** [comment]
When a prop is given inline to the component, Vue will call `===` on its previous value to decide if it fires the relevant watcher. Array references / functions / object are never strict equal to eachother, unless it's the same reference. If you put the value in `data`, you can compare by reference, and thus no needless watch calls -> requests happen

**Comment by marekalgoud** [comment]
Ok it's clear for me now :)

Thanks.

**Comment by kevintruby** [comment]
You guys are life savers. I struggled with this issue for a day, and the fix outlined above resolved my own issue as well.

My situation was slightly different -- I have multiple custom menu widgets extending the `RefinementList` component via `createWidgetMixin({ connector: connectRefinementList })`, and in some cases with a pre-filtered SSR result set, it was possible if a facet refinement in effect for the first refinement list menu to trigger multiple queries in reaction to responsive behavior; wherein the multiple requests must have shared a competing, non-filtered state, as the page would then update to lose all active filters and the entire index would be served.

I think the Vue-InstantSearch documentation for `ais-refinement-list` could probably use a small note about this pass-by-reference gotcha, since it uses an inline array literal as the example:

```vue
<ais-refinement-list
  [...]
  :sort-by="['isRefined', 'name:asc']"
/>
```

**Comment by Haroenv** [comment]
That's a good point, i'll look into fixing this in the docs
