### ISSUE TITLE
'highlightedTagName' not working with ais-snippet

### ISSUE THREAD

**Issue by IHIutch** [algolia/vue-instantsearch#727]
**Bug 🐞**

### What is the current behavior?

Result always comes back in `<mark>` tags.

### Make a sandbox with the current behavior

https://codesandbox.io/s/vue-instantsearch-app-4xff0?fontsize=14

### What is the expected behavior?

Result comes back in whatever I specify in 'highlightedTagName'; eg. `<span>` or `<em>`.

### What is the version you are using?

2.5.0

**Comment by samouss** [comment]
Hi @IHIutch, I didn't understood the problem. Form what I've tested inside the example when a value is provided to `highlightedTagName` that results are displayed with it. I've used `mark` instead of `span` inside your example. Here is what I've got (see below). 

Could you provide a bit more context? That would help to better understand the problem? Thanks!

```
<ais-highlight
  class="font-medium"
  attribute="hierarchy.lvl0"
  :hit="item"
  highlightedTagName="mark"
  :class-names="{
    'ais-Highlight-highlighted': 'bg-gray-400 rounded-sm'
  }"
/>
```

![Screenshot 2019-10-03 at 16 48 28](https://user-images.githubusercontent.com/6513513/66137614-a341dd00-e5fd-11e9-8216-5c94cc54e6ee.png)

**Comment by IHIutch** [comment]
I was referring to the <ais-snippet> component specifically. And <mark> is the default so using that as the test probably won't yield accurate results anyway.

If you type 'testing' you'll see the snippet component (yellow background)

**Comment by samouss** [comment]
My bad. You're correct the replacement is done on `em` instead of `mark`. It has been fixed on [`ais-highlight`](https://github.com/algolia/vue-instantsearch/pull/679) but not `ais-snippet`. Thanks for the report!

@Haroenv we should probably move to the InstantSearch `highlight`/`snippet` function, it would have fixed those kind of issues.

**Comment by IHIutch** [comment]
No problem :)
