### ISSUE TITLE
VueInstantsearch is using old version of algoliasearch-helper-js

### ISSUE THREAD

**Issue by jdanino** [algolia/vue-instantsearch#755]
**Bug 🐞**

Im working with Vue Instantsearch in a nuxt SSR setup but am running into a problem that seems to have already been fixed here: https://github.com/algolia/algoliasearch-helper-js/commit/e68ecfe9897e630443ce72618a832291c0151df8 
When I manually make the same change it works fine.

It seems that the vue instantsearch package is running behind on both the algoliasearch-helper and instantsearch.js package.  Anything that can be done about this?

Versions I'm using:

└─┬ vue-instantsearch@2.6.0
  └─┬ instantsearch.js@3.7.0
├─┬ algoliasearch-helper@2.28.0

Thanks!

**Comment by francoischalifour** [comment]
The JavaScript Helper (`algoliasearch-helper-js`) is used as the internal state management of InstantSearch. The v3 brings breaking changes that Vue InstantSearch 2 will not support.

Vue InstantSearch 3 will include the JavaScript Helper 3 and so your problem will likely get fixed.

Do you mind sharing what problem you're having with Nuxt?

**Comment by jdanino** [comment]
Thanks for the quick reply. 

I meant I was running into the problem where the removeHierarchicalFacetRefinement method returns an error if the refinement is not defined. It seems to have been fixed in v3 of the helper but not in vue-instantsearch yet a it is not using v3 of the helper, as I now understand. Any idea as to when vue-instantsearch v3 will be released?

I ran into some trouble with nuxt and instantsearch when trying to use menu's instead of refinements and then having to figure out which state to set in the findResultsState method as this is not documented.  Turned out i had to use the hierarchicalFacets.  

The other thing I found quite challenging is to really customize the routing (more seo friendly urls using the path) while using the vue router that nuxt uses. It feels that the documentation there might be running a bit behind? (theres also a link to a non working sampe: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue+InstantSearch/routing-seo-friendly)

**Comment by Haroenv** [comment]
looks like the name of the folders got switched up, that should be: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue+InstantSearch/routing-full-url

**Comment by Haroenv** [comment]
> Any idea as to when vue-instantsearch v3 will be released?

Soon! We are now working on making sure it will be fully compatible with upcoming major versions of other libraries more lower in the stack. If you can not wait, and really want to try it out, you can use the code on the `next` branch here.

**Comment by Haroenv** [comment]
For routing with the Vue Router, you can use the code as here: https://github.com/algolia/doc-code-samples/blob/master/Vue%20InstantSearch/routing-vue-router/src/views/Home.vue#L56

With the difference that you don't _just_ use `query`, but any URL format you want

**Comment by biancajemsten** [comment]
Hey 👋 Just chiming in here as I'm having an issue that seems to be rooted in the same problem. 
Merely loading in InstantSearch from vue-instant-search is causing the browser to throw the error below. Since lodash was removed in algoliasearch-helper 3.0 I'm guessing it could have something to do with that? 

```index.js?c402:468 Uncaught TypeError: forOwn is not a function
    at new SearchParameters (index.js?c402:468)
    at eval (index.js?c402:480)
    at Object.../../node_modules/algoliasearch-helper/src/SearchParameters/index.js (app.js:1223)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at eval (algoliasearch.helper.js?b05a:3)
    at Object.../../node_modules/algoliasearch-helper/src/algoliasearch.helper.js (app.js:1271)
    at __webpack_require__ (app.js:833)
    at fn (app.js:130)
    at eval (index.js?497f:3)
```

In my yarn.lock file instantsearch has an algoliasearch-helper dependency of 2.26.0 and 
vue-instant-search has an algoliasearch-helper dependency of 2.28.1. 

I'm using the following: 
└─┬ vue-instantsearch@2.7.0
└─┬ algoliasearch@4.2.0

Any advice on this?

**Comment by Haroenv** [comment]
I don't think that's related @biancajemsten, could you create a GitHub repo or codesandbox which gives this problem

**Comment by biancajemsten** [comment]
Hey @Haroenv thanks for the super quick response yesterday. You're right it wasn't related, had a hard time recreating the issue in a sandbox. But this was the issue in case anyone else comes across the same thing.

I'm using gridsome so in the end it turned out to be this line of code in chainWebpack  the `gridsome.config.js` : 
`config.resolve.alias.set('lodash', 'lodash-es');` 

Must have messed something up in the lodash dependencies of InstantSearch! 🤷‍♀️

**Comment by Haroenv** [comment]
Thanks for sharing your solution!
