### ISSUE TITLE
Ais-Toggle-Refinement does not generate a correct url

### ISSUE THREAD

**Issue by gabz57** [algolia/vue-instantsearch#778]
**Bug 🐞**

### What is the current behavior?

On our search page, we use 2 checkboxes relative to the same boolean value :
```
<ais-toggle-refinement attribute="is_published" label="Publié" :on="true">
  [...]
</ais-toggle-refinement>
<ais-toggle-refinement attribute="is_published" label="Non Publié" :on="false">
  [...]
</ais-toggle-refinement>
```
The client query/response works as expected, we obtain the correct results from algolia.
But, the url generated on the client side contains in both cases the value 'true' for the given attribute :

```
| ais-toggle-refinement | on=true | on=false | => url
| checked               |    X    |          | ?toggle%5Bis_published%5D=true
| checked               |         |    X     | ?toggle%5Bis_published%5D=true
| checked               |    X    |    X     | ?toggle%5Bis_published%5D=true

```

This prevent us from creating stable URLs with preselected options, currently if I select any checkbox and refresh the page, both are checked (here appears the trouble), but the results are the previous one (which is what I expected anyway).

Also,  the value from the scope method **isRefine** for the component with **on="false"** does not returns the value one could expect here, I always have the refinement set to **'true'**, as a consequence when we refresh the page both checkboxes are checked.

### Make a sandbox with the current behavior

Template: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch

### What is the expected behavior?
```
| ais-toggle-refinement | on=true | on=false | => url
| checked               |    X    |          | ?toggle%5Bis_published%5D=true
| checked               |         |    X     | ?toggle%5Bis_published%5D=false
| checked               |    X    |    X     | ?toggle%5Bis_published%5D=true&toggle%5Bis_published%5D=false
```

On page refresh, the selection from the user is preserved and coherent

### Does this happen only in specific situations?
No, we have this behavior using a boolean value, but I suppose this could be extended to string values

### What is the proposed solution?

I am not certain if this is a bug or a limitation, HTTP accepts repeating such values in a url, I've been digging a bit in the component source code, the url generation depends on a connector for this component but I haven't been further.

Looking at the **request.query.facetFilters** field within http call, one can see the expected values (which is why the results are corrects) : 

When only the on="true" checkbox is checked : 
```
facetFilters: [["is_published:true"]]
```
When only the on="false" checkbox is checked : 
```
facetFilters: [["is_published:false"]]
```
When both checkbox are checked : 
```
facetFilters: [["is_published:false","is_published:true"]]
```

I wonder if the URL construction shouldn't simply follow the same rules than the query ?

### What is the version you are using?
vue-instantsearch: 2.7.0

**Comment by Haroenv** [comment]
This is a limitation of our internals for toggle which only sets a single value per attribute, since we (wrongly, I guess) assumed that it would override instead of toggling both. 

The solution here would be a breaking change for us, since it changes the format of the refinement to an array, however you can make that change yourself:

1. copy AisToggleRefinement's contents
2. change the connectToggleRefinement import to a self-made connectToggleRefinement fork
3. find this line: https://github.com/algolia/instantsearch.js/blob/29610532809af4015a142b6c03783d6e069597b8/src/connectors/toggle-refinement/connectToggleRefinement.js#L262

change it to an array of values which are currently refined (check if isRefined is true, then either include the current "on" value, or else remove the current "on" value from the list. Make sure to also have symmetrical values here: https://github.com/algolia/instantsearch.js/blob/29610532809af4015a142b6c03783d6e069597b8/src/connectors/toggle-refinement/connectToggleRefinement.js#L272

A different solution which is slightly more hacky, but would work without forking anything is by having "attribute aliases". This is done by the following steps:

1. use two different attributes (e.g. `is_published` & `is_published_alt`)
2. make a custom search client (wrapping the existing search client)
3. in the `search` method, first replace `is_published_alt` back to `is_published`
4. in the `search` method, after the response, add back `is_published_alt` with the same value as `is_published`

A totally different solution without being hacky is to use two separate attributes (`is_published` & `is_not_published`) and use those in the refinement.

Hope that gives you some options

**Comment by gabz57** [comment]
Waw, such a great response in such a short time ! Thank you a lot !

- I understand the first suggestion which is what I supposed to be buggy, but requires to override an external component (for us, which is something we avoid to benefit from updates without surprise).
- The second suggestion is interesting, I will check with my team if it is acceptable
- The last suggestion is also what I found as a not ideal (it requires us to duplicate data only for this purpose) but perfectly working solution
