### ISSUE TITLE
Multi-index search and SEO URL are not fully compatible

### ISSUE THREAD

**Issue by sukei** [algolia/vue-instantsearch#820]
**Bug 🐞**

### What is the current behavior?

When using multi-index using the new `ais-index` widget, the nested widget states are stored into the global state under the index key. But the filters that should be inherited from the parent widgets are not serialized into that state. Then, it's not possible to map the state to route (and the reverse) since some filters are missing.

### What is the expected behavior?

```vue
<ais-instant-search :search-client="searchClient" index-name="indexA" :routing="routing">
  <ais-search-box />

  <ais-index index-name="indexA">
    <ais-toggle-refinement attribute="attributeA" :on="true" :off="false" />
  </ais-index>

  <ais-index index-name="indexB">
    <ais-toggle-refinement attribute="attributeB" :on="true" :off="false" />
  </ais-index>
</ais-instant-search>
```

```js
const routing = {
  router: history(),
  stateMapping: {
    stateToRoute(uiState) {
      console.log(uiState);

      return uiState;
    },
    ...
  }
};
```

Got:

```json
{
  "indexA": {
    "toggle": {
      "attributeA": true
    }
  },
  "indexB": {
    "toggle": {
      "attributeB": true
    }
  }
}
```

Has you can see, the `query` filter is missing from the state. Expect:

```json
{
  "indexA": {
    "toggle": {
      "attributeA": true,
      "query": "foo"
    }
  },
  "indexB": {
    "toggle": {
      "attributeB": true,
      "query": "foo"
    }
  }
}
```

### Does this happen only in specific situations?

Happen when using `ais-index` and trying to inherit from parent widget state.

### What is the proposed solution?

Serialize down the tree the values of the inherited filters are change the structure of the state to keep them somewhere.

### What is the version you are using?

`^4.3.0`

**Comment by Haroenv** [comment]
This seems to be related to a duplicated index widget. I understand that this might not have been documented clearly, but repeating an index widget with the same index name, without index-id is not something for which we have found a suitable heuristic. Because of this the routing is not working. However in your case you have two options:

1. use index-id if you want to do a separate query for that index: https://codesandbox.io/s/great-visvesvaraya-7fwqs?file=/src/App.vue
2. not using ais-index for the root index display: https://codesandbox.io/s/recursing-cdn-7zhcj?file=/src/App.vue

Hope that helps, but if your use case relies on the current behaviour, except for routing, we might need to find an alternative solutoin

**Comment by sukei** [comment]
I just tried to set the `index-id` for each usage of the `ais-index` and it fixes the issue in a satisfying manner for me. Thanks for this @Haroenv.

However, the second one can't work for my usage. Since the root index make usage of widgets to filter attributes that my sub-indices didn't define. As a result, my sub-indices can't get any result because it looks for values in attributes that didn't exist.

BTW, since the introduction of `ais-index`, should we keep the `ais-instant-search` `index-name` prop mandatory? It's something that confuses me at first. It's perfectly understandable when looking at the current resulting state. But, what about building something like that instead:

```json
{
  "root": {
    "query": "foo",
    "page": 2
  },
  "indices": {
    "indexA": {
      "toggle": {
        "attributeA": true
      }
    },
    "indexB": {
      "toggle": {
        "attributeB": true
      }
    }
  }
}
```

```
/search?query=foo&page=2&indexA[toggle][attributeA]=true&indexB[toggle][attributeB]=true
```

It gives you the opportunity to make usage of cross-indices widgets. On the other hand, it should merge each individual `ais-index` widgets instead of overriding them.

WDYT?

**Comment by Haroenv** [comment]
The reason there's an index name on root, is because you can imagine the whole app being wrapped by an ais-index. In a future version we could think on making that more explicit, however we wanted a minimal migration guide / code size for those not using multi-index.

Merging could be an interesting option, but we did not go with that with the initial multi-index implementation, since it could cause infinite loops fairly trivially. It's something we can iterate on in the future though.

We have decided to keep the search state flat, to make iterating over it for retrieving the queries to send straightforward, as well as routing being slightly simpler if you know in advance what type of keys to expect.

Thanks a lot for your suggestions though, it really gives something to think about

**Comment by sukei** [comment]
Don't worry, I understand your concerns about existing code-base and the difficulty to make it work without going too far.

Whatever, thanks you for your time.
