### ISSUE TITLE
Memory leak in nuxt

### ISSUE THREAD

**Issue by bootsmann1995** [algolia/vue-instantsearch#834]
I get a memory leak some times in serve and every time on build: 
the errors are following: 
Serve: 
![image](https://user-images.githubusercontent.com/65391517/89618033-9c25d400-d88b-11ea-865a-ab771931c556.png)
build: 
![image](https://user-images.githubusercontent.com/65391517/89618080-b790df00-d88b-11ea-9754-233a52a4cc5b.png)

im using the V3 setup, algolia has in its documentation: https://codesandbox.io/s/github/algolia/vue-instantsearch/tree/master/examples/nuxt

here is my code: 
![image](https://user-images.githubusercontent.com/65391517/89618260-0c345a00-d88c-11ea-9b5c-4ec8c061b4ef.png)

**Comment by Haroenv** [comment]
Hi @bootsmann1995, the code you sent is in a screenshot, which means that we can't run that. It seems like there are some differences between the existing component and this one. 

To note as well, that the component which has `serverPrefetch` can not also have `asyncData`, since both have the same goal, and would become an infinite loop otherwise

Could you create your example code in a repository or sandbox please?

**Comment by Haroenv** [comment]
As I believe this hasn't been reported since, I think you found a solution, so I'll close this issue now. Thanks for reporting!
